# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
     cache:
       class: Doctrine\Common\Cache\FilesystemCache
       arguments: ['../var/cache']

     app.helper:
       class: AppBundle\Utils\Helper
       arguments: ['@doctrine.orm.entity_manager']

     app.OrderService:
       class: AppBundle\Services\OrderService
       arguments: ['@doctrine.orm.entity_manager', "@=service('security.token_storage').getToken().getUser()", "@knp_paginator"]

     app.ItemService:
       class: AppBundle\Services\ItemService
       arguments: ['@doctrine.orm.entity_manager', "@=service('security.token_storage').getToken().getUser()"]

     app.RestaurantService:
       class: AppBundle\Services\RestaurantService
       arguments: ['@doctrine.orm.entity_manager']

     app.AdminService:
       class: AppBundle\Services\AdminService
       arguments: ['@doctrine.orm.entity_manager', '@cache']

     api:
       class: AppBundle\Utils\ApiUtil
