<?php

namespace AppBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTotal(){
      return $this->getEntityManager()
            ->createQuery(
                'SELECT count(i) FROM AppBundle:Item i'
            )
            ->getSingleScalarResult();
    }
}
