<?php

namespace AppBundle\Repository;

/**
 * RestaurantPhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantPhoneRepository extends \Doctrine\ORM\EntityRepository
{
}
